### ISSUE TITLE
`mkdocs` config not compatible with version 0.17.5

### ISSUE THREAD

**Issue by alkamid** [stevengj/mpb#59]
When trying to build using `mkdocs.yml` form master with `mkdocs-0.17.5`, all pages in documentation are empty. In `0.17.0` the old theme config syntax was deprecated. To be compatible with the current version, the syntax should be:
```yaml
theme:
  name: readthedocs
  custom_dir: mpb-mkdocs-theme
```
PR: https://github.com/stevengj/mpb/pull/60.
